import type { FloorPlan, Unit, Viewpoint } from "../types";
import viewpointData from "./viewpoints.json";

/** Blender 360° viewpoints per plan (generated by blender/render_interiors.py). */
export const PLAN_VIEWPOINTS = viewpointData as unknown as Record<string, Viewpoint[]>;

// ------------------------------------------------------------------
// PLAN A — 3LDK, wide-span corner residence (~108 m²)
// Envelope 12.8 × 9.6 m (incl. 1.2 m balcony), glazing on the south view side.
// ------------------------------------------------------------------
const PLAN_A: FloorPlan = {
  id: "A",
  name: "PLAN A",
  layout: "3LDK",
  widthM: 12.8,
  depthM: 9.6,
  ceilingM: 2.7,
  glazedSides: ["bottom"],
  rooms: [
    { id: "bd2", kind: "bedroom", label: "ベッドルーム2", sub: "6.0帖", x: 0, z: 0, w: 4.0, d: 4.0, floor: "carpet" },
    { id: "bath", kind: "bath", label: "バスルーム", x: 4.0, z: 0, w: 1.2, d: 2.2, floor: "tile" },
    { id: "pdr", kind: "powder", label: "洗面室", x: 4.0, z: 2.2, w: 1.2, d: 1.8, floor: "tile" },
    { id: "entry", kind: "entry", label: "玄関", x: 5.2, z: 0, w: 2.2, d: 1.8, floor: "marble" },
    { id: "cor", kind: "corridor", label: "", x: 5.2, z: 1.8, w: 2.2, d: 2.2, floor: "marble" },
    { id: "wc", kind: "toilet", label: "トイレ", x: 7.4, z: 0, w: 1.4, d: 1.8, floor: "tile" },
    { id: "wic", kind: "wic", label: "WIC", x: 7.4, z: 1.8, w: 1.4, d: 2.2, floor: "oak" },
    { id: "bd3", kind: "bedroom", label: "ベッドルーム3 / 書斎", sub: "5.2帖", x: 8.8, z: 0, w: 4.0, d: 4.0, floor: "oak" },
    { id: "mbr", kind: "master", label: "主寝室", sub: "8.0帖", x: 0, z: 4.0, w: 4.0, d: 4.4, floor: "carpet" },
    { id: "ldk", kind: "ldk", label: "リビング・ダイニング・キッチン", sub: "20.5帖", x: 4.0, z: 4.0, w: 8.8, d: 4.4, floor: "oak" },
    { id: "bal", kind: "balcony", label: "バルコニー", x: 0, z: 8.4, w: 12.8, d: 1.2, floor: "deck" },
  ],
  furniture: [
    // Living
    { kind: "rug", x: 8.2, z: 6.6, scale: 1.15 },
    { kind: "sectional", x: 8.2, z: 6.0, rot: 0 },
    { kind: "coffeeTable", x: 8.2, z: 7.1, rot: 0 },
    { kind: "tvBoard", x: 8.2, z: 8.0, rot: 0 },
    { kind: "plant", x: 12.2, z: 7.9, rot: 0 },
    { kind: "artwork", x: 4.15, z: 5.6, rot: 90 },
    // Dining
    { kind: "diningTable", x: 10.8, z: 5.4, rot: 0 },
    { kind: "pendant", x: 10.8, z: 5.4, rot: 0 },
    // Kitchen
    { kind: "kitchen", x: 6.1, z: 4.55, rot: 0 },
    { kind: "island", x: 6.1, z: 5.7, rot: 0 },
    // Master
    { kind: "bedDouble", x: 2.0, z: 6.1, rot: 0 },
    { kind: "nightstand", x: 0.5, z: 5.2, rot: 0 },
    { kind: "nightstand", x: 3.5, z: 5.2, rot: 0 },
    { kind: "artwork", x: 2.0, z: 4.15, rot: 0 },
    // Bedroom 2
    { kind: "bed", x: 1.3, z: 2.2, rot: 90 },
    { kind: "desk", x: 3.4, z: 1.0, rot: 90 },
    // Bedroom 3 / study
    { kind: "desk", x: 12.2, z: 2.2, rot: 90 },
    { kind: "lounge", x: 9.8, z: 3.0, rot: 30 },
    { kind: "shelf", x: 10.8, z: 0.45, rot: 180 },
  ],
};

// ------------------------------------------------------------------
// PLAN B — 2LDK (~75 m²)
// Envelope 10.0 × 8.4 m (incl. 1.0 m balcony).
// ------------------------------------------------------------------
const PLAN_B: FloorPlan = {
  id: "B",
  name: "PLAN B",
  layout: "2LDK",
  widthM: 10.0,
  depthM: 8.4,
  ceilingM: 2.6,
  glazedSides: ["bottom"],
  rooms: [
    { id: "bd2", kind: "bedroom", label: "ベッドルーム", sub: "6.0帖", x: 0, z: 0, w: 4.0, d: 3.4, floor: "carpet" },
    { id: "entry", kind: "entry", label: "玄関", x: 4.0, z: 0, w: 2.0, d: 1.6, floor: "marble" },
    { id: "cor", kind: "corridor", label: "", x: 4.0, z: 1.6, w: 2.0, d: 1.8, floor: "marble" },
    { id: "bath", kind: "bath", label: "バスルーム", x: 6.0, z: 0, w: 1.8, d: 2.0, floor: "tile" },
    { id: "pdr", kind: "powder", label: "洗面室", x: 6.0, z: 2.0, w: 1.8, d: 1.4, floor: "tile" },
    { id: "wc", kind: "toilet", label: "トイレ", x: 7.8, z: 0, w: 2.2, d: 1.6, floor: "tile" },
    { id: "wic", kind: "wic", label: "WIC", x: 7.8, z: 1.6, w: 2.2, d: 1.8, floor: "oak" },
    { id: "mbr", kind: "master", label: "主寝室", sub: "7.0帖", x: 0, z: 3.4, w: 3.4, d: 4.0, floor: "carpet" },
    { id: "ldk", kind: "ldk", label: "リビング・ダイニング・キッチン", sub: "16.5帖", x: 3.4, z: 3.4, w: 6.6, d: 4.0, floor: "oak" },
    { id: "bal", kind: "balcony", label: "バルコニー", x: 0, z: 7.4, w: 10.0, d: 1.0, floor: "deck" },
  ],
  furniture: [
    { kind: "rug", x: 6.4, z: 5.5, scale: 1.0 },
    { kind: "sectional", x: 6.2, z: 4.9, rot: 0 },
    { kind: "coffeeTable", x: 6.2, z: 5.9, rot: 0 },
    { kind: "tvBoard", x: 6.2, z: 7.0, rot: 0 },
    { kind: "diningTable", x: 8.7, z: 4.5, rot: 0 },
    { kind: "pendant", x: 8.7, z: 4.5, rot: 0 },
    { kind: "kitchen", x: 4.2, z: 3.85, rot: 0 },
    { kind: "island", x: 4.5, z: 4.9, rot: 0 },
    { kind: "plant", x: 9.4, z: 6.8, rot: 0 },
    { kind: "bedDouble", x: 1.7, z: 5.3, rot: 0 },
    { kind: "nightstand", x: 0.5, z: 4.5, rot: 0 },
    { kind: "artwork", x: 1.7, z: 3.55, rot: 0 },
    { kind: "bed", x: 1.3, z: 1.8, rot: 90 },
    { kind: "desk", x: 3.4, z: 0.9, rot: 90 },
  ],
};

// ------------------------------------------------------------------
// PLAN C — 1LDK premium pied-à-terre (~52 m²)
// Envelope 8.0 × 7.6 m (incl. 1.0 m balcony).
// ------------------------------------------------------------------
const PLAN_C: FloorPlan = {
  id: "C",
  name: "PLAN C",
  layout: "1LDK",
  widthM: 8.0,
  depthM: 7.6,
  ceilingM: 2.55,
  glazedSides: ["bottom"],
  rooms: [
    { id: "bd", kind: "bedroom", label: "ベッドルーム", sub: "6.0帖", x: 0, z: 0, w: 3.0, d: 3.0, floor: "carpet" },
    { id: "entry", kind: "entry", label: "玄関", x: 3.0, z: 0, w: 1.8, d: 1.6, floor: "marble" },
    { id: "cor", kind: "corridor", label: "", x: 3.0, z: 1.6, w: 1.8, d: 1.4, floor: "marble" },
    { id: "bath", kind: "bath", label: "バスルーム", x: 4.8, z: 0, w: 1.6, d: 1.8, floor: "tile" },
    { id: "pdr", kind: "powder", label: "洗面室", x: 4.8, z: 1.8, w: 1.6, d: 1.2, floor: "tile" },
    { id: "wc", kind: "toilet", label: "トイレ", x: 6.4, z: 0, w: 1.6, d: 1.6, floor: "tile" },
    { id: "wic", kind: "wic", label: "WIC", x: 6.4, z: 1.6, w: 1.6, d: 1.4, floor: "oak" },
    { id: "ldk", kind: "ldk", label: "リビング・ダイニング・キッチン", sub: "14.0帖", x: 0, z: 3.0, w: 8.0, d: 3.6, floor: "oak" },
    { id: "bal", kind: "balcony", label: "バルコニー", x: 0, z: 6.6, w: 8.0, d: 1.0, floor: "deck" },
  ],
  furniture: [
    { kind: "rug", x: 3.4, z: 4.9, scale: 0.95 },
    { kind: "sectional", x: 3.2, z: 4.3, rot: 0 },
    { kind: "coffeeTable", x: 3.2, z: 5.2, rot: 0 },
    { kind: "tvBoard", x: 3.2, z: 6.2, rot: 0 },
    { kind: "diningTable", x: 6.4, z: 4.1, rot: 0, scale: 0.9 },
    { kind: "pendant", x: 6.4, z: 4.1, rot: 0 },
    { kind: "kitchen", x: 1.3, z: 3.35, rot: 0 },
    { kind: "island", x: 2.0, z: 4.3, rot: 0 },
    { kind: "plant", x: 7.4, z: 6.0, rot: 0 },
    { kind: "bedDouble", x: 1.5, z: 1.6, rot: 0, scale: 0.9 },
    { kind: "nightstand", x: 2.6, z: 0.8, rot: 0 },
  ],
};

export const PLANS: Record<string, FloorPlan> = {
  A: PLAN_A,
  B: PLAN_B,
  C: PLAN_C,
};

export const UNITS: Unit[] = [
  { id: "u1", residenceNo: "32-01", floor: 32, layout: "3LDK", areaM2: 108.4, facing: "S", priceOku: 3.28, status: "available", planId: "A", tagline: "南面ワイドスパンを誇る、最上級プレミアフロア。", tower: { colFrac: 0.22 } },
  { id: "u2", residenceNo: "31-02", floor: 31, layout: "2LDK", areaM2: 75.2, facing: "SE", priceOku: 2.18, status: "available", planId: "B", tagline: "都心の夜景を独り占めにする、南東の角住戸。", tower: { colFrac: 0.5 } },
  { id: "u3", residenceNo: "30-03", floor: 30, layout: "1LDK", areaM2: 52.6, facing: "SW", priceOku: 1.48, status: "available", planId: "C", tagline: "洗練を凝縮した、上質なセカンドレジデンス。", tower: { colFrac: 0.78 } },
  { id: "u4", residenceNo: "28-01", floor: 28, layout: "3LDK", areaM2: 108.4, facing: "S", priceOku: 2.98, status: "negotiating", planId: "A", tagline: "光と風が抜ける、ゆとりの角住戸。", tower: { colFrac: 0.22 } },
  { id: "u5", residenceNo: "25-02", floor: 25, layout: "2LDK", areaM2: 75.2, facing: "S", priceOku: 1.92, status: "available", planId: "B", tagline: "陽光あふれる、まっすぐな南向き。", tower: { colFrac: 0.5 } },
  { id: "u6", residenceNo: "22-03", floor: 22, layout: "1LDK", areaM2: 52.6, facing: "E", priceOku: 1.28, status: "sold", planId: "C", tagline: "朝日とともに目覚める東向き住戸。", tower: { colFrac: 0.78 } },
  { id: "u7", residenceNo: "20-01", floor: 20, layout: "3LDK", areaM2: 108.4, facing: "SW", priceOku: 2.68, status: "available", planId: "A", tagline: "豊かな緑を見下ろす、リビング。", tower: { colFrac: 0.22 } },
  { id: "u8", residenceNo: "18-02", floor: 18, layout: "2LDK", areaM2: 75.2, facing: "SE", priceOku: 1.72, status: "available", planId: "B", tagline: "暮らしやすさが息づく、中層階。", tower: { colFrac: 0.5 } },
];

export const TOTAL_FLOORS = 34;
